// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC82opcKvlkUy8xy-K9B2iMLQb4x4OrtsU',
    appId: '1:57311557501:web:cbcbc9b503c05520f3fe14',
    messagingSenderId: '57311557501',
    projectId: 'sgt-visitor-app',
    authDomain: 'sgt-visitor-app.firebaseapp.com',
    storageBucket: 'sgt-visitor-app.firebasestorage.app',
    measurementId: 'G-ETFHG8CMZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVwyqsaq-rWOMK8NQij99Kae0MouRSFVQ',
    appId: '1:57311557501:android:b30a96fe9c706e78f3fe14',
    messagingSenderId: '57311557501',
    projectId: 'sgt-visitor-app',
    storageBucket: 'sgt-visitor-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmTPT27IM4YCrGh-l6aO1GgTIPRaYSEK4',
    appId: '1:57311557501:ios:58808f4e5fc7b5aff3fe14',
    messagingSenderId: '57311557501',
    projectId: 'sgt-visitor-app',
    storageBucket: 'sgt-visitor-app.firebasestorage.app',
    iosBundleId: 'com.example.myCrossPlatformApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmTPT27IM4YCrGh-l6aO1GgTIPRaYSEK4',
    appId: '1:57311557501:ios:58808f4e5fc7b5aff3fe14',
    messagingSenderId: '57311557501',
    projectId: 'sgt-visitor-app',
    storageBucket: 'sgt-visitor-app.firebasestorage.app',
    iosBundleId: 'com.example.myCrossPlatformApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC82opcKvlkUy8xy-K9B2iMLQb4x4OrtsU',
    appId: '1:57311557501:web:6122032640a1b649f3fe14',
    messagingSenderId: '57311557501',
    projectId: 'sgt-visitor-app',
    authDomain: 'sgt-visitor-app.firebaseapp.com',
    storageBucket: 'sgt-visitor-app.firebasestorage.app',
    measurementId: 'G-WBQHHWQ0SN',
  );

}